#!/bin/bash
# Test BMS Document Generator Pipeline
# Verifies document generation capabilities

set -e

echo "=================================================="
echo "Testing BMS Document Generator Pipeline"
echo "=================================================="
echo ""

# Check if Pipelines container is running
if ! docker ps --format '{{.Names}}' | grep -q "^pipelines$"; then
    echo "❌ Pipelines container not running"
    exit 1
fi

echo "Test 1: Check pipeline file exists..."
if docker exec pipelines test -f /app/pipelines/bms_document_generator.py; then
    echo "✅ Pipeline file found"
else
    echo "❌ Pipeline file not found"
    exit 1
fi

echo ""
echo "Test 2: Check Python dependencies..."
MISSING_DEPS=0

echo -n "  - python-docx: "
if docker exec pipelines python -c "import docx" 2>/dev/null; then
    echo "✅ Installed"
else
    echo "❌ Missing"
    MISSING_DEPS=1
fi

echo -n "  - openpyxl: "
if docker exec pipelines python -c "import openpyxl" 2>/dev/null; then
    echo "✅ Installed"
else
    echo "❌ Missing"
    MISSING_DEPS=1
fi

echo -n "  - python-pptx: "
if docker exec pipelines python -c "import pptx" 2>/dev/null; then
    echo "✅ Installed"
else
    echo "❌ Missing"
    MISSING_DEPS=1
fi

if [ $MISSING_DEPS -eq 1 ]; then
    echo ""
    echo "⚠️  Some dependencies missing. Run:"
    echo "  bash pipelines/install-document-pipeline.sh"
    exit 1
fi

echo ""
echo "Test 3: Check output directory..."
if docker exec pipelines test -d /app/pipelines/output; then
    echo "✅ Output directory exists"
else
    echo "⚠️  Creating output directory..."
    docker exec pipelines mkdir -p /app/pipelines/output
fi

echo ""
echo "Test 4: Test Word document generation..."
docker exec pipelines python << 'EOF'
from docx import Document
import os

doc = Document()
doc.add_heading('Test Document', 0)
doc.add_paragraph('This is a test document generated by BMS Document Generator Pipeline.')

output_path = '/app/pipelines/output/test_word.docx'
doc.save(output_path)

if os.path.exists(output_path):
    size = os.path.getsize(output_path)
    print(f"✅ Word document created: {size} bytes")
else:
    print("❌ Word document creation failed")
    exit(1)
EOF

echo ""
echo "Test 5: Test Excel spreadsheet generation..."
docker exec pipelines python << 'EOF'
from openpyxl import Workbook
import os

wb = Workbook()
ws = wb.active
ws.title = "Test Sheet"
ws.append(["Column 1", "Column 2", "Column 3"])
ws.append(["Data 1", "Data 2", "Data 3"])

output_path = '/app/pipelines/output/test_excel.xlsx'
wb.save(output_path)

if os.path.exists(output_path):
    size = os.path.getsize(output_path)
    print(f"✅ Excel spreadsheet created: {size} bytes")
else:
    print("❌ Excel spreadsheet creation failed")
    exit(1)
EOF

echo ""
echo "Test 6: Test PowerPoint presentation generation..."
docker exec pipelines python << 'EOF'
from pptx import Presentation
import os

prs = Presentation()
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
title.text = "Test Presentation"

output_path = '/app/pipelines/output/test_presentation.pptx'
prs.save(output_path)

if os.path.exists(output_path):
    size = os.path.getsize(output_path)
    print(f"✅ PowerPoint presentation created: {size} bytes")
else:
    print("❌ PowerPoint presentation creation failed")
    exit(1)
EOF

echo ""
echo "Test 7: List generated test files..."
docker exec pipelines ls -lh /app/pipelines/output/ | grep test_

echo ""
echo "=================================================="
echo "✅ All Tests Passed"
echo "=================================================="
echo ""
echo "Document generation capabilities verified:"
echo "  ✅ Word (DOCX) - python-docx working"
echo "  ✅ Excel (XLSX) - openpyxl working"
echo "  ✅ PowerPoint (PPTX) - python-pptx working"
echo ""
echo "Next Steps:"
echo ""
echo "1. Connect to OpenWebUI (if not already):"
echo "   - Admin Panel → Settings → Connections"
echo "   - Add: http://localhost:9099 with key: 0p3n-w3bu!"
echo ""
echo "2. Enable for your model:"
echo "   - Workspace → Models → Edit"
echo "   - Enable 'BMS Document Generator' pipeline"
echo ""
echo "3. Test in chat:"
echo "   - 'Create a Word document with vendor evaluation form'"
echo "   - 'Generate an Excel spreadsheet comparing departments'"
echo "   - 'Make a PowerPoint presentation about safety procedures'"
echo ""
echo "4. Download generated files:"
echo "   - docker cp pipelines:/app/pipelines/output/. ./downloads/"
echo ""
echo "View logs: docker logs pipelines -f"
echo ""
