#!/bin/bash
# Test BMS Document Generator Pipeline (Pod Environment)
# Verifies document generation capabilities without Docker

set -e

echo "=================================================="
echo "Testing BMS Document Generator Pipeline (Pod)"
echo "=================================================="
echo ""

PIPELINES_DIR="/workspace/001-bms-agent/pipelines"
OUTPUT_DIR="/workspace/001-bms-agent/pipelines/output"

echo "Test 1: Check pipeline file exists..."
if [ -f "$PIPELINES_DIR/bms_document_generator.py" ]; then
    echo "✅ Pipeline file found"
else
    echo "❌ Pipeline file not found: $PIPELINES_DIR/bms_document_generator.py"
    exit 1
fi

echo ""
echo "Test 2: Check Python dependencies..."
MISSING_DEPS=0

echo -n "  - python-docx: "
if python3 -c "import docx" 2>/dev/null; then
    echo "✅ Installed"
else
    echo "❌ Missing"
    MISSING_DEPS=1
fi

echo -n "  - openpyxl: "
if python3 -c "import openpyxl" 2>/dev/null; then
    echo "✅ Installed"
else
    echo "❌ Missing"
    MISSING_DEPS=1
fi

echo -n "  - python-pptx: "
if python3 -c "import pptx" 2>/dev/null; then
    echo "✅ Installed"
else
    echo "❌ Missing"
    MISSING_DEPS=1
fi

if [ $MISSING_DEPS -eq 1 ]; then
    echo ""
    echo "⚠️  Some dependencies missing. Run:"
    echo "  bash pipelines/install-document-pipeline.sh"
    exit 1
fi

echo ""
echo "Test 3: Check output directory..."
if [ -d "$OUTPUT_DIR" ]; then
    echo "✅ Output directory exists"
else
    echo "⚠️  Creating output directory..."
    mkdir -p "$OUTPUT_DIR"
fi

echo ""
echo "Test 4: Test Word document generation..."
python3 << EOF
from docx import Document
import os

doc = Document()
doc.add_heading('Test Document', 0)
doc.add_paragraph('This is a test document generated by BMS Document Generator Pipeline.')

output_path = '$OUTPUT_DIR/test_word.docx'
doc.save(output_path)

if os.path.exists(output_path):
    size = os.path.getsize(output_path)
    print(f"✅ Word document created: {size} bytes")
else:
    print("❌ Word document creation failed")
    exit(1)
EOF

echo ""
echo "Test 5: Test Excel spreadsheet generation..."
python3 << EOF
from openpyxl import Workbook
import os

wb = Workbook()
ws = wb.active
ws.title = "Test Sheet"
ws.append(["Column 1", "Column 2", "Column 3"])
ws.append(["Data 1", "Data 2", "Data 3"])

output_path = '$OUTPUT_DIR/test_excel.xlsx'
wb.save(output_path)

if os.path.exists(output_path):
    size = os.path.getsize(output_path)
    print(f"✅ Excel spreadsheet created: {size} bytes")
else:
    print("❌ Excel spreadsheet creation failed")
    exit(1)
EOF

echo ""
echo "Test 6: Test PowerPoint presentation generation..."
python3 << EOF
from pptx import Presentation
import os

prs = Presentation()
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
title.text = "Test Presentation"

output_path = '$OUTPUT_DIR/test_presentation.pptx'
prs.save(output_path)

if os.path.exists(output_path):
    size = os.path.getsize(output_path)
    print(f"✅ PowerPoint presentation created: {size} bytes")
else:
    print("❌ PowerPoint presentation creation failed")
    exit(1)
EOF

echo ""
echo "Test 7: List generated test files..."
ls -lh "$OUTPUT_DIR" | grep test_ || echo "  (No test files found)"

echo ""
echo "Test 8: Check Pipelines server status..."
if [ -f "$PIPELINES_DIR/server.pid" ]; then
    PID=$(cat "$PIPELINES_DIR/server.pid")
    if ps -p $PID > /dev/null 2>&1; then
        echo "✅ Pipelines server running (PID: $PID)"
    else
        echo "⚠️  Pipelines server not running (stale PID file)"
    fi
else
    echo "⚠️  Pipelines server PID file not found"
fi

echo ""
echo "Test 9: Check server health endpoint..."
if curl -s http://localhost:9099/health > /dev/null 2>&1; then
    echo "✅ Server health check passed"
else
    echo "⚠️  Server not responding on port 9099"
    echo "   Start server with: bash pipelines/deploy-pipelines-server.sh"
fi

echo ""
echo "=================================================="
echo "✅ All Tests Passed"
echo "=================================================="
echo ""
echo "Document generation capabilities verified:"
echo "  ✅ Word (DOCX) - python-docx working"
echo "  ✅ Excel (XLSX) - openpyxl working"
echo "  ✅ PowerPoint (PPTX) - python-pptx working"
echo ""
echo "Generated test files:"
echo "  - $OUTPUT_DIR/test_word.docx"
echo "  - $OUTPUT_DIR/test_excel.xlsx"
echo "  - $OUTPUT_DIR/test_presentation.pptx"
echo ""
echo "Next Steps:"
echo ""
echo "1. Connect to OpenWebUI (if not already):"
echo "   - Admin Panel → Settings → Connections"
echo "   - Add: http://localhost:9099 with key: 0p3n-w3bu!"
echo ""
echo "2. Enable for your model:"
echo "   - Workspace → Models → Edit"
echo "   - Enable 'BMS Document Generator' pipeline"
echo ""
echo "3. Test in chat:"
echo "   - 'Create a Word document with vendor evaluation form'"
echo "   - 'Generate an Excel spreadsheet comparing departments'"
echo "   - 'Make a PowerPoint presentation about safety procedures'"
echo ""
echo "4. Download generated files:"
echo "   - Files are in: $OUTPUT_DIR"
echo "   - Copy to local: cp $OUTPUT_DIR/*.docx ~/downloads/"
echo ""
echo "View server logs: tail -f $PIPELINES_DIR/server.log"
echo "Stop server: kill \$(cat $PIPELINES_DIR/server.pid)"
echo ""
